### ISSUE TITLE
Netlabel doesn't work on Security Onion (Linux)

### ISSUE THREAD

**Issue by Reg1nleifr** [dreadl0ck/netcap#11]
Hey Phil, 
I've been cross compiling your project for the latest Security Onion version (16.04.5.6).
Netcap seems to work fine, however netlabel doesn't work at all.  So far I haven't had time to investigate any further however I thought I'd let you know. Hopefully I'll be back with some useful information soon.

Thanks for your awesome project & BR
Reg1n

**Comment by dreadl0ck** [comment]
Hi there,

thanks for reporting!

Please share some output and the commands you executed for reproducing the issue.

Note that netlabel calls suricata to obtain label information,
and currently the path for the configuration file is hardcoded:

https://github.com/dreadl0ck/netcap/blob/master/label/suricata.go#L104

Probably suricata wasn't installed or the configuration file was not at the specified path.

Cheers

**Comment by dreadl0ck** [comment]
Closed due to age. Contact me by mail to reopen.
