### ISSUE TITLE
How can I cross-compile a statically link executables for android platform device?

### ISSUE THREAD

**Issue by Droid-MAX** [dreadl0ck/netcap#17]
I have tried many methods, but I have failed to compile all the tools successfully. By modifying the CGO_ENABLED and ldflags parameters, I will prompt pcap related error, but the libpcap-dev package is installed on the host system.

**Comment by Droid-MAX** [comment]
https://github.com/google/gopacket/issues/100#issuecomment-363427138

**Comment by Droid-MAX** [comment]
After successful compilation, put the executable file into the mobile phone system environment to perform an error, prompting runtime error.

**Comment by dreadl0ck** [comment]
Please show what commands for compilation you used, and the runtime error message.
Also what OS are you on, which version of Go and what version of libc do you have installed?
