### ISSUE TITLE
Error when installing netcap on Ubuntu18

### ISSUE THREAD

**Issue by Jgerardopine** [dreadl0ck/netcap#18]
Description:

When installing netcap on an Ubuntu18 setup on VisualStucio code I get the following error:

> github.com/dreadl0ck/netcap/encoder
>go/src/github.com/dreadl0ck/netcap/encoder/tls.go:51:17: hello.Unmarshall undefined (type tlsx.ClientHello has no field or method Unmarshall)
>go/src/github.com/dreadl0ck/netcap/encoder/tls.go:55:3: use of untyped nil
>go/src/github.com/dreadl0ck/netcap/encoder/tls.go:131:37: cannot use hello (type *tlsx.ClientHello) as type *tlsx.ClientHelloBasic in argument to ja3.DigestHex

Do I need to install some additionl package on Linux or is there a specific verison that I should use?

**Comment by dreadl0ck** [comment]
Hi there, thanks for reporting!

What version of Go are you using? 
Make sure you compile with go modules enabled, it should pick the correct version of the tlsx package then.

Starting in Go 1.13, module mode will be the default for all development.
https://blog.golang.org/using-go-modules
