### ISSUE TITLE
How to reference events across log files

### ISSUE THREAD

**Issue by 1computerguy** [dreadl0ck/netcap#19]
Is there currently a method to reference correlated events across log output files? I know zeek adds a UID field to correlate events across various files, is there a similar method with NetCap to do the same thing?

**Comment by dreadl0ck** [comment]
Not implemented at the moment, but will consider adding this to the next major release. 

Flow and Connection types have a UID, but it's not set on derived audit records yet.

Will likely also switch to their community-id-spec (https://github.com/corelight/community-id-spec) for the Connection UIDs.

Thanks for the heads up!
