### ISSUE TITLE
"Net" command throws error

### ISSUE THREAD

**Issue by LiteACE** [dreadl0ck/netcap#20]
Hi,

I followed the detailed steps to download Netcap for Kali, but when i punched in "net" in my terminal. I was thrown with "Invalid command:net". May i know what is the cause or there are configuration issues that I have errored.

Error:
┌──(kali㉿kali)-[~/…/src/github.com/dreadl0ck/netcap]
└─$ net                                                                  1 ⚙
Invalid command: net

**Comment by dreadl0ck** [comment]
Hi,

that an error from your shell because it can't find the binary.

Did you update your zshrc and source it afterwards in the current shell?

Otherwise you can always invoke netcap from its installation path:

    $ /usr/local/bin/netcap
