### ISSUE TITLE
v0.6.0 Compiled versions

### ISSUE THREAD

**Issue by laven807** [dreadl0ck/netcap#21]
Hi，
    does v0.6.0 have compiled files, pls?

**Comment by dreadl0ck** [comment]
Hi,

I had to apply some fixes to the release scripts,
you can find the latest version with binaries here: https://github.com/dreadl0ck/netcap/releases/tag/v0.6.5

The releases that have *nodpi* in the archive name do not have bindings to the deep packet inspection libraries,
and can be executed without libndpi and libprotoident being installed on the system.
