### ISSUE TITLE
Renaming of netcap binary?

### ISSUE THREAD

**Issue by tonylambiris** [dreadl0ck/netcap#5]
I'm creating a package for this to push to the Arch Linux AUR, and I was wondering what your thoughts were on renaming the **netcap** binary to something that won't conflict with the libcap-ng library:
```
➜ pacman -Qo `which netcap`
/usr/bin/netcap is owned by libcap-ng 0.7.9-1
```
Perhaps something like **netcapper** or **gonetcap**?

Thoughts?

Thanks!

**Comment by dreadl0ck** [comment]
Thanks for creating an AUR package!

What about *ncap* to keep it short?
Would also be a good hint which program to use for working with *.ncap* files :)

**Comment by dreadl0ck** [comment]
Interesting, I don't get any results when throwing in the names in the archlinux AUR search:

https://aur.archlinux.org/packages/?O=0&K=ncap
https://aur.archlinux.org/packages/?O=0&K=netcap

For macOS, the name netcap seems to be free, also in brew there is currently no package with that name.

What about: **networkcap** or **netcapture** for AUR?

That would still preserve the use case of the tool in the name,
and is only 4 chars longer. (Although probably everyone will use tab completion anyway)

Personally I like **netcapture** better.

Suggestions, anyone?

**Comment by tonylambiris** [comment]
Thoughts on calling it ncapr or netcapper?

**Comment by tonylambiris** [comment]
```
➜ pacman -Qi netcap-git
Name            : netcap-git
Version         : 1:r74.9067552-1
Description     : A framework for secure and scalable network traffic analysis
Architecture    : x86_64
URL             : https://github.com/dreadl0ck/netcap
Licenses        : GPL3
Groups          : None
Provides        : netcap
Depends On      : None
Optional Deps   : None
Required By     : None
Optional For    : None
Conflicts With  : netcap
Replaces        : None
Installed Size  : 10.31 MiB
Packager        : Tony Lambiris <tony.lambiris@criticalstack.com>
Build Date      : Sun 30 Dec 2018 08:17:10 PM EST
Install Date    : Sun 30 Dec 2018 08:18:44 PM EST
Install Reason  : Explicitly installed
Install Script  : No
Validated By    : None

➜ pacman -Qlp netcap-git-1:r74.9067552-1-x86_64.pkg.tar.xz
netcap-git /usr/
netcap-git /usr/bin/
netcap-git /usr/bin/netcapture
netcap-git /usr/share/
netcap-git /usr/share/licenses/
netcap-git /usr/share/licenses/netcap-git/
netcap-git /usr/share/licenses/netcap-git/LICENSE
```

**Comment by dreadl0ck** [comment]
Awesome, thanks!
